export const uris = [
  'http://search.yahoo.com/mrss/', // Official URI.
  'https://search.yahoo.com/mrss/',
  'http://search.yahoo.com/mrss',
  'https://search.yahoo.com/mrss',
  'http://video.search.yahoo.com/mrss',
  'http://video.search.yahoo.com/mrss/',
  'https://video.search.yahoo.com/mrss',
  'https://video.search.yahoo.com/mrss/',
  'http://www.rssboard.org/media-rss',
  'http://www.rssboard.org/media-rss/',
  'https://www.rssboard.org/media-rss',
  'https://www.rssboard.org/media-rss/',
  'http://search.yahoo.com/searchmonkey/media/',
  'https://search.yahoo.com/searchmonkey/media/',
  'http://search.yahoo.com/searchmonkey/media',
  'https://search.yahoo.com/searchmonkey/media',
  'http://tools.search.yahoo.com/mrss/',
  'https://tools.search.yahoo.com/mrss/',
  'http://tools.search.yahoo.com/mrss',
  'https://tools.search.yahoo.com/mrss',
]

export const stopNodes = [
  '*.media:rating',
  '*.media:adult',
  '*.media:title',
  '*.media:description',
  '*.media:category',
  '*.media:hash',
  '*.media:credit',
  '*.media:copyright',
  '*.media:text',
  '*.media:restriction',
  '*.media:keywords',
  '*.media:comment',
  '*.media:response',
  '*.media:backlink',
  '*.media:license',
  '*.media:location',
  '*.media:param',
  '*.media:scene.scenetitle',
  '*.media:scene.scenedescription',
  '*.media:scene.scenestarttime',
  '*.media:scene.sceneendtime',
]
