import { describe, expect, it } from 'bun:test'
import { generateItemOrFeed } from './utils.js'

describe('generateItemOrFeed', () => {
  it('should generate valid itemOrFeed object with all properties', () => {
    const value = {
      abstract: 'Sample abstract content',
      accessRights: 'Open Access',
      accrualMethod: 'Manual upload',
      accrualPeriodicity: 'Annual',
      accrualPolicy: 'Open submission',
      alternative: 'Alternative Title',
      audience: 'General Public',
      available: new Date('2023-06-01T00:00:00Z'),
      bibliographicCitation: 'Doe, J. (2023). Sample Work. Publisher.',
      conformsTo: 'Dublin Core Metadata Terms',
      contributor: 'Jane Smith',
      coverage: 'Global',
      created: new Date('2023-05-01T12:00:00Z'),
      creator: 'John Doe',
      date: new Date('2023-05-02T08:30:00Z'),
      dateAccepted: new Date('2023-05-10T09:00:00Z'),
      dateCopyrighted: new Date('2023-05-15T00:00:00Z'),
      dateSubmitted: new Date('2023-05-05T14:30:00Z'),
      description: 'A comprehensive description',
      educationLevel: 'Graduate level',
      extent: '250 pages',
      format: 'application/pdf',
      hasFormat: 'https://example.org/formats/pdf',
      hasPart: 'https://example.org/parts/chapter1',
      hasVersion: 'https://example.org/versions/v2',
      identifier: 'ISBN:978-0123456789',
      instructionalMethod: 'Online learning',
      isFormatOf: 'https://example.org/original',
      isPartOf: 'https://example.org/collection',
      isReferencedBy: 'https://example.org/references/citation1',
      isReplacedBy: 'https://example.org/replacement',
      isRequiredBy: 'https://example.org/dependent',
      issued: new Date('2023-05-20T10:00:00Z'),
      isVersionOf: 'https://example.org/original-work',
      language: 'en-US',
      license: 'Creative Commons Attribution 4.0',
      mediator: 'Library System',
      medium: 'Digital',
      modified: new Date('2023-05-25T16:45:00Z'),
      provenance: 'Digitized from original manuscript',
      publisher: 'Academic Press',
      references: 'https://example.org/ref/source1',
      relation: 'https://example.org/related',
      replaces: 'https://example.org/old-version',
      requires: 'https://example.org/prerequisite',
      rights: 'Copyright 2023',
      rightsHolder: 'Example University',
      source: 'https://example.org/source',
      spatial: 'Boston, MA, USA',
      subject: 'Academic Research',
      tableOfContents: 'Chapter 1, Chapter 2, Chapter 3',
      temporal: '2023',
      title: 'Sample Title',
      type: 'Text',
      valid: new Date('2024-05-25T23:59:59Z'),
    }
    const expected = {
      'dcterms:abstract': 'Sample abstract content',
      'dcterms:accessRights': 'Open Access',
      'dcterms:accrualMethod': 'Manual upload',
      'dcterms:accrualPeriodicity': 'Annual',
      'dcterms:accrualPolicy': 'Open submission',
      'dcterms:alternative': 'Alternative Title',
      'dcterms:audience': 'General Public',
      'dcterms:available': '2023-06-01T00:00:00.000Z',
      'dcterms:bibliographicCitation': 'Doe, J. (2023). Sample Work. Publisher.',
      'dcterms:conformsTo': 'Dublin Core Metadata Terms',
      'dcterms:contributor': 'Jane Smith',
      'dcterms:coverage': 'Global',
      'dcterms:created': '2023-05-01T12:00:00.000Z',
      'dcterms:creator': 'John Doe',
      'dcterms:date': '2023-05-02T08:30:00.000Z',
      'dcterms:dateAccepted': '2023-05-10T09:00:00.000Z',
      'dcterms:dateCopyrighted': '2023-05-15T00:00:00.000Z',
      'dcterms:dateSubmitted': '2023-05-05T14:30:00.000Z',
      'dcterms:description': 'A comprehensive description',
      'dcterms:educationLevel': 'Graduate level',
      'dcterms:extent': '250 pages',
      'dcterms:format': 'application/pdf',
      'dcterms:hasFormat': 'https://example.org/formats/pdf',
      'dcterms:hasPart': 'https://example.org/parts/chapter1',
      'dcterms:hasVersion': 'https://example.org/versions/v2',
      'dcterms:identifier': 'ISBN:978-0123456789',
      'dcterms:instructionalMethod': 'Online learning',
      'dcterms:isFormatOf': 'https://example.org/original',
      'dcterms:isPartOf': 'https://example.org/collection',
      'dcterms:isReferencedBy': 'https://example.org/references/citation1',
      'dcterms:isReplacedBy': 'https://example.org/replacement',
      'dcterms:isRequiredBy': 'https://example.org/dependent',
      'dcterms:issued': '2023-05-20T10:00:00.000Z',
      'dcterms:isVersionOf': 'https://example.org/original-work',
      'dcterms:language': 'en-US',
      'dcterms:license': 'Creative Commons Attribution 4.0',
      'dcterms:mediator': 'Library System',
      'dcterms:medium': 'Digital',
      'dcterms:modified': '2023-05-25T16:45:00.000Z',
      'dcterms:provenance': 'Digitized from original manuscript',
      'dcterms:publisher': 'Academic Press',
      'dcterms:references': 'https://example.org/ref/source1',
      'dcterms:relation': 'https://example.org/related',
      'dcterms:replaces': 'https://example.org/old-version',
      'dcterms:requires': 'https://example.org/prerequisite',
      'dcterms:rights': 'Copyright 2023',
      'dcterms:rightsHolder': 'Example University',
      'dcterms:source': 'https://example.org/source',
      'dcterms:spatial': 'Boston, MA, USA',
      'dcterms:subject': 'Academic Research',
      'dcterms:tableOfContents': 'Chapter 1, Chapter 2, Chapter 3',
      'dcterms:temporal': '2023',
      'dcterms:title': 'Sample Title',
      'dcterms:type': 'Text',
      'dcterms:valid': '2024-05-25T23:59:59.000Z',
    }

    expect(generateItemOrFeed(value)).toEqual(expected)
  })

  it('should generate itemOrFeed with minimal properties', () => {
    const value = {
      title: 'Minimal Title',
    }
    const expected = {
      'dcterms:title': 'Minimal Title',
    }

    expect(generateItemOrFeed(value)).toEqual(expected)
  })

  it('should handle object with only undefined/empty properties', () => {
    const value = {
      abstract: undefined,
      accessRights: undefined,
      accrualMethod: undefined,
      accrualPeriodicity: undefined,
      accrualPolicy: undefined,
      alternative: undefined,
      audience: undefined,
      available: undefined,
      bibliographicCitation: undefined,
      conformsTo: undefined,
      contributor: undefined,
      coverage: undefined,
      created: undefined,
      creator: undefined,
      date: undefined,
      dateAccepted: undefined,
      dateCopyrighted: undefined,
      dateSubmitted: undefined,
      description: undefined,
      educationLevel: undefined,
      extent: undefined,
      format: undefined,
      hasFormat: undefined,
      hasPart: undefined,
      hasVersion: undefined,
      identifier: undefined,
      instructionalMethod: undefined,
      isFormatOf: undefined,
      isPartOf: undefined,
      isReferencedBy: undefined,
      isReplacedBy: undefined,
      isRequiredBy: undefined,
      issued: undefined,
      isVersionOf: undefined,
      language: undefined,
      license: undefined,
      mediator: undefined,
      medium: undefined,
      modified: undefined,
      provenance: undefined,
      publisher: undefined,
      references: undefined,
      relation: undefined,
      replaces: undefined,
      requires: undefined,
      rights: undefined,
      rightsHolder: undefined,
      source: undefined,
      spatial: undefined,
      subject: undefined,
      tableOfContents: undefined,
      temporal: undefined,
      title: undefined,
      type: undefined,
      valid: undefined,
    }

    expect(generateItemOrFeed(value)).toBeUndefined()
  })

  it('should handle empty object', () => {
    const value = {}

    expect(generateItemOrFeed(value)).toBeUndefined()
  })

  it('should handle non-object inputs gracefully', () => {
    expect(generateItemOrFeed(undefined)).toBeUndefined()
  })
})
