import type { DateLike } from '../../../common/types.js'

export type ItemOrFeed<TDate extends DateLike> = {
  abstract?: string
  accessRights?: string
  accrualMethod?: string
  accrualPeriodicity?: string
  accrualPolicy?: string
  alternative?: string
  audience?: string
  available?: TDate
  bibliographicCitation?: string
  conformsTo?: string
  contributor?: string
  coverage?: string
  created?: TDate
  creator?: string
  date?: TDate
  dateAccepted?: TDate
  dateCopyrighted?: TDate
  dateSubmitted?: TDate
  description?: string
  educationLevel?: string
  extent?: string
  format?: string
  hasFormat?: string
  hasPart?: string
  hasVersion?: string
  identifier?: string
  instructionalMethod?: string
  isFormatOf?: string
  isPartOf?: string
  isReferencedBy?: string
  isReplacedBy?: string
  isRequiredBy?: string
  issued?: TDate
  isVersionOf?: string
  language?: string
  license?: string
  mediator?: string
  medium?: string
  modified?: TDate
  provenance?: string
  publisher?: string
  references?: string
  relation?: string
  replaces?: string
  requires?: string
  rights?: string
  rightsHolder?: string
  source?: string
  spatial?: string
  subject?: string
  tableOfContents?: string
  temporal?: string
  title?: string
  type?: string
  valid?: TDate
}
